classDiagram
    GameObject <|-- Entity
    GameObject <|-- UIObject

    Component <|-- MovementComponent
    Component <|-- PhysicsComponent
    Component <|-- VisualComponent

    Creature <|-- Avatar
    Creature <|-- ZombieAI

    Entity <|-- Creature
    Entity <|-- Gunshot
    Entity <|-- Item
    Entity <|-- Obstacle
    Entity o-- Component

    HitBox <|-- CircleHitBox
    HitBox <|-- RectangleHitBox

    Item <|-- Grenade

    MovementComponent <|-- AIComponent
    MovementComponent <|-- PlayerInputComponent
    MovementComponent <|-- StaticMovementComponent

    Obstacle <|-- Tree

    PhysicsComponent <|-- DynamicPhysicsComponent 
    PhysicsComponent <|-- StaticPhysicsComponent  
    PhysicsComponent o-- HitBox 
    PhysicsComponent -- PhysicsSystem

    PlayerInputComponent -- InputSystem

    TextObject <|-- GrenadeCounterText
    TextObject <|-- HelpText
    TextObject <|-- ZombieCounterText

    UIObject <|-- TextObject
    UIObject -- GraphicsSystem
    UIObject -- InputSystem
    
    VisualComponent <|-- CircleComponent
    VisualComponent <|-- RectangleComponent
    VisualComponent <|-- SpriteComponent
    VisualComponent -- GraphicsSystem

    class Creature {
        
    }
    <<Abstract>> Creature

    class Entity {
        # components : Component [*]
        type()* : int 
    }
    <<Abstract>> Entity


    class GameObject {
        # posX : double
        # posZ : double
        world : World$
        
        + update(deltaTime : double) : void
        + draw() : void
    }
    <<Abstract>> GameObject


    class Item {

    }
    <<Abstract>> Item


    class Obstacle {
        
    }
    <<Abstract>> Obstacle


    class UIObject {
        
    }
    <<Abstract>> UIObject



    class HitBox {

    }
    <<Abstract>> HitBox

    class CircleHitBox {
        # radius : int 
    }

    class RectangleHitBox {
        # width : int 
        # height : int 
    }


    class Component {
        + update(deltaTime : double) : void
    }

    class VisualComponent {
        + draw() : void 
    }

    class MovementComponent {
        # alpha : double
        # speed : double
    }
    <<Abstract>> MovementComponent

    class PhysicsComponent {
        # hitBox : HitBox
        physicsSystem : PhysicsSystem$
    }

    class CircleComponent {
        # radius : int 
        # color : Color
    }

    class RectangleComponent {
        # width : int 
        # height : int 
        # color : Color
    }

    class PlayerInputComponent {
        
    }

    class PhysicsSystem {
        - instance : PhysicsSystem $
        - PhysicsSystem()
        + getInstance() : PhysicsSystem$
    }
    <<Singleton>> PhysicsSystem

    class GraphicsSystem {
        - instance : GraphicsSystem $
        - GraphicsSystem()
        + getInstance() : GraphicsSystem$
    }
    <<Singleton>> GraphicsSystem

    class InputSystem {
        - instance : InputSystem $
        - InputSystem()
        + getInstance() : InputSystem$
    }
    <<Singleton>> InputSystem